
import java.sql.Connection;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import java.util.Vector;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author GACA1186
 */
public class JDetalle_x_Vendedora extends javax.swing.JFrame {
    private JConeccion JBase_Datos;
    private Connection Cn;
    
    private Vector Cab;
    private Vector Det;
    private Vector Fila;
    
    private String NumeroFormato = "###,###,###,###.##";
    private DecimalFormat JFormato ;
    /**
     * Creates new form JDetalle_x_Vendedora
     */
    public JDetalle_x_Vendedora(JConeccion JBase_Datos3, Connection Cn2, String Id_Vendedora, String Fecha) {
        this.JBase_Datos = JBase_Datos3;
        this.Cn = Cn2;
        this.Cab = new Vector();
        this.Fila = new Vector();
        this.Cab.add("Vendedora");
        this.Cab.add("Codigo");
        this.Cab.add("Nombre del Articulo");
        this.Cab.add("Cantidad");
        this.Cab.add("Costo Unitario-Comision");
        this.Cab.add("Costo Total-Comision");
        this.Cab.add("Venta Unitaria");
        initComponents();
         JFormato= new DecimalFormat(NumeroFormato);
        getDetalle(Id_Vendedora, Fecha);
    }

    
    public void getDetalle(String P_IdVendedora, String P_Fecha){
        try {
            String Str_Sql =" SELECT idVendedora , T2.Plu,  NombreLargo,T2.Cantidad, T2.PrecioUnitario, Costo       \n" +
                            " FROM JCabFactura as T1 , JDetFactura as T2 , JArticulos as T3       \n" +
                            " Where T1.Numero=T2.Numero AND T2.Plu=T3.Plu and fecha='"+P_Fecha+"' and T1.Estado ='C'     "
                            + " and idVendedora='"+P_IdVendedora+"'";
            
           ResultSet Rs =  JBase_Datos.SQL_QRY(this.Cn,Str_Sql);
           Fila.clear();
           double cantidad = 0, Precio=0, Costo=0, total_comision=0;
           while(Rs.next()){
               this.Det = new Vector();
               Det.add(Rs.getString("idVendedora"));
               Det.add(Rs.getString("Plu"));
               Det.add(Rs.getString("NombreLargo"));
              
               double tmp_cantidad = Rs.getInt("Cantidad");
               double tmp_precio  = Rs.getDouble("PrecioUnitario");
               double tmp_costo = Rs.getDouble("Costo");
               
               cantidad = cantidad +tmp_cantidad;
               Costo = Costo + tmp_costo;
               Precio = Precio + tmp_precio;
               total_comision = total_comision + tmp_costo*tmp_cantidad;
               Det.add(this.JFormato.format(tmp_cantidad));
               Det.add(this.JFormato.format(tmp_costo));
               Det.add(this.JFormato.format(tmp_costo*tmp_cantidad));
               Det.add(this.JFormato.format(tmp_precio));
               this.Fila.add(Det);
               
           }
           
           if(cantidad > 0){
               this.Det = new Vector();
               Det.add("Total");
               Det.add("----");
               Det.add("---->");
               Det.add(this.JFormato.format(cantidad));
               Det.add(this.JFormato.format(0));
               Det.add(this.JFormato.format(total_comision));
               Det.add(this.JFormato.format(0));
               this.Fila.add(Det);
           }
           
           
           jC_Detalle_Vendedor.setModel(new javax.swing.table.DefaultTableModel(this.Fila, this.Cab));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"getDetalle(String P_IdVendedora, String P_Fecha) "+e.getMessage());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jC_Detalle_Vendedor = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jC_Detalle_Vendedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vendedora", "Codigo", "Nombre del Articulo", "Cantidad", "Costo Unitario-Comision", "Comision Total", "Venta Unitaria"
            }
        ));
        jScrollPane1.setViewportView(jC_Detalle_Vendedor);

        jButton1.setText("Cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 923, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Detalle", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDetalle_x_Vendedora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDetalle_x_Vendedora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDetalle_x_Vendedora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDetalle_x_Vendedora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JDetalle_x_Vendedora(null, null, null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JTable jC_Detalle_Vendedor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
