
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JInternalFrame;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.print.*;
import javax.print.attribute.HashPrintRequestAttributeSet;
import javax.print.attribute.PrintRequestAttributeSet;
import javax.print.attribute.standard.MediaSizeName;
import javax.swing.JOptionPane;
import javax.swing.JTextPane;
import javax.swing.table.DefaultTableModel;


/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Garyn Carrillo
 */
public class JFacturacion  extends JInternalFrame{

    /**
     * Creates new form JFacturacion
     */
    private JLectorCodigoBarra CodigoBarra;
    private JCentroCostos  CentroVenta;
    private JCajero_Pos Caja;
    private JArticulos Articulo;
    private JConeccion JBase_Datos;
    private Connection Cn;
    private Vector Cabecera ;
    private Vector Art_Detalle;
    private Vector Detalle  ;
    private JBuscar_Articulo Fr_Articulo;
    private Vector Cabecera_Medio;
    private Vector M_Detalle;
    private Vector Detalle_Medio;
    private JFactura Factura;
    private double AcomuladoIva;
    private double AcomuladoOtroImpuesto;
    private double AcomuladoTotal_Pagar;
    private double Acomula_Medios_pagos;
    private int PosionActual;
    private String NumeroFormato = "###,###,###,###.##";
    private DecimalFormat JFormato ;
    private double Cantidad;
    private JMedios MediosPagos;
    private JPrincipal  Principal;
    private double Acomulado_Plan_Separe;
    private boolean SwCodigoBarra ;
    private double Descontar;
    private double Valor_Descuento_General;
    private double ItemFactura ;
    public JFacturacion(JPrincipal Pr , JConeccion JBase_Datos3, Connection Cn2, JCentroCostos Centro, JCajero_Pos Caja) {
        //CodigoBarra = new JLectorCodigoBarra(this);
       SwCodigoBarra = false;
       this.ItemFactura = 0;
       this.Principal = Pr;
       this.JBase_Datos = JBase_Datos3;
       this.Cn = Cn2;
       JFormato= new DecimalFormat(NumeroFormato);
       this. Acomulado_Plan_Separe = 0;
       initComponents();
       this.CentroVenta = Centro;
       this.Caja = Caja;
       this.JTxtNombreCajero.setText(this.Caja.getNombre());
       this.JTxtFecha.setText(this.getFecha());
       Articulo = new JArticulos(this.JBase_Datos, this.Cn);
       Cabecera =  new Vector();
       Art_Detalle  = new  Vector();
       this.Valor_Descuento_General = 0;
       this.Cabecera_Medio = new Vector();
       this.M_Detalle = new Vector();
       this.PosionActual = -1;
       this.getAsignarMediosPagos();
       this.JLNumeroDocumento.setVisible(false);
       this.JTxtDocumento.setVisible(false);
       
       AcomuladoIva = 0;
       AcomuladoOtroImpuesto= 0;
       AcomuladoTotal_Pagar= 0;
       Acomula_Medios_pagos= 0;
       Factura = new JFactura(this.JBase_Datos, this.Cn);
       this.JTxtNombreCajero.setText(this.Caja.getNombre().trim());
       
       Cabecera.add("Plu");
       Cabecera.add("Detalle");
       Cabecera.add("Cantidad");
       Cabecera.add("Precio Unitario");
       Cabecera.add("Precio Total");
       
       TxtNoFactura.setText(this.getNumroFactura());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        TxtNoFactura = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        JTxtFecha = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        JTxtNombreCajero = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTablaArticulos = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JBAgregar = new javax.swing.JButton();
        JTxtCantidad = new javax.swing.JTextField();
        JTxtPlu = new javax.swing.JTextField();
        jCodigoBarra = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTxtDescuento = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        JTxtMedioPago = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        JTxtIva = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        JTxtOtros = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        JTxtTotalPagar = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        JTxtCambio = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        JBFacturacion = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        JTxtValor = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        JCTipoMedioPago = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        JTxtDocumento = new javax.swing.JTextField();
        JLNumeroDocumento = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jBGuardar = new javax.swing.JButton();
        jBImprimir = new javax.swing.JButton();
        jBNuevo = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Generacion de Factura");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Factura No");

        TxtNoFactura.setEditable(false);

        jTextField4.setEditable(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Fecha:");

        JTxtFecha.setEditable(false);
        JTxtFecha.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Cajero:");

        JTxtNombreCajero.setEditable(false);
        JTxtNombreCajero.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(TxtNoFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(JTxtNombreCajero, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(JTxtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TxtNoFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(JTxtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(JTxtNombreCajero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        JTablaArticulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Plu", "Descripcion", "Cantidad", "Precio Unitario", "Precio Total"
            }
        ));
        jScrollPane1.setViewportView(JTablaArticulos);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Plu");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Cantidad");

        JBAgregar.setText("Agregar");
        JBAgregar.setNextFocusableComponent(JCTipoMedioPago);
        JBAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBAgregarActionPerformed(evt);
            }
        });

        JTxtCantidad.setNextFocusableComponent(JBAgregar);

        JTxtPlu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTxtPluActionPerformed(evt);
            }
        });
        JTxtPlu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JTxtPluKeyPressed(evt);
            }
        });

        jCodigoBarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCodigoBarraActionPerformed(evt);
            }
        });
        jCodigoBarra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jCodigoBarraKeyPressed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Codigo de Barra");

        jTxtDescuento.setText("0");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("Descuento");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jCodigoBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JBAgregar))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(JTxtPlu, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(71, 71, 71)
                                    .addComponent(jLabel16))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(JTxtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(37, 37, 37)
                                    .addComponent(jTxtDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTxtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTxtPlu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCodigoBarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBAgregar))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        JTxtMedioPago.setEditable(false);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Forma de Pago");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Total a Pagar");

        JTxtIva.setEditable(false);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("I.V.A.");

        JTxtOtros.setEditable(false);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Otros Impuestos");

        JTxtTotalPagar.setEditable(false);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Total a Pagar");

        JTxtCambio.setEditable(false);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Cambio");

        jTextField9.setEditable(false);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Saldo Plan Separe");

        JBFacturacion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        JBFacturacion.setText("FACTURAR");
        JBFacturacion.setNextFocusableComponent(jBGuardar);
        JBFacturacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBFacturacionActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setText("Cerrar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Valor");

        JCTipoMedioPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCTipoMedioPagoActionPerformed(evt);
            }
        });
        JCTipoMedioPago.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JCTipoMedioPagoKeyPressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Tipo de Pago");

        JLNumeroDocumento.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        JLNumeroDocumento.setText("Numero del Documento");

        jButton6.setText("Ir...");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jButton6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton6KeyPressed(evt);
            }
        });

        jButton1.setText("Agregar");
        jButton1.setNextFocusableComponent(JBFacturacion);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(42, 42, 42))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JCTipoMedioPago, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(JTxtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(58, 58, 58))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLNumeroDocumento)
                    .addComponent(JTxtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JCTipoMedioPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTxtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JLNumeroDocumento)
                .addGap(18, 18, 18)
                .addComponent(JTxtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton6))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jBGuardar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBGuardar.setText("Guardar");
        jBGuardar.setNextFocusableComponent(jBImprimir);
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });

        jBImprimir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBImprimir.setText("Imprimir");
        jBImprimir.setNextFocusableComponent(jBNuevo);
        jBImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBImprimirActionPerformed(evt);
            }
        });

        jBNuevo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBNuevo.setText("Nueva");
        jBNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(52, 52, 52)
                                .addComponent(jLabel13)
                                .addGap(59, 59, 59)
                                .addComponent(jLabel12))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(JTxtMedioPago, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JTxtIva, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel7)))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(JTxtOtros, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JTxtTotalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(JTxtCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel9)
                                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBImprimir)
                            .addComponent(jBNuevo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                            .addComponent(jBGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(JBFacturacion, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9)
                                .addComponent(jLabel8)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JTxtIva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTxtOtros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addComponent(jLabel10)
                        .addGap(3, 3, 3)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(JTxtTotalPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JTxtCambio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(JTxtMedioPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JBFacturacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jBGuardar)
                                    .addComponent(jBImprimir))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton4)
                                    .addComponent(jBNuevo)))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 46, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jButton5.setText("Eliminar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton5)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addGap(15, 15, 15)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenu1.setMnemonic('E');
        jMenu1.setText("Ejecutar");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Imprimir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Nueva Factura");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Descuento General");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenu3.setText("Anular");

        jMenuItem3.setText("Factura");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenu1.add(jMenu3);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMenuItem5.setText("Salir");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(JTablaArticulos.getRowCount()==0){
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(this,"Para poder salir debes Sacar la mercancia de Pantalla");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jCodigoBarraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCodigoBarraKeyPressed
        // TODO add your handling code here:
       if (evt.getKeyCode()==115){
           Fr_Articulo = new JBuscar_Articulo(this.JBase_Datos, this.Cn, this);
           Fr_Articulo.setBounds(30,80, 500, 310);
           Fr_Articulo.setVisible(true);
       }
    }//GEN-LAST:event_jCodigoBarraKeyPressed

    private void jCodigoBarraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCodigoBarraActionPerformed
        // TODO add your handling code here:
         if(!jCodigoBarra.getText().trim().equals("")){
             if (this.Articulo.getArticulo_CodigoBarra(this.jCodigoBarra.getText().trim())){
                 SwCodigoBarra = true;
                 JTxtCantidad.setText("1");
                 this.AgregarProducto();
                 JTxtCantidad.setText("");
                 
             }else{
                 JOptionPane.showMessageDialog(this," Articulo no existe ");
             }
         }
         
    }//GEN-LAST:event_jCodigoBarraActionPerformed

    private void JBFacturacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBFacturacionActionPerformed
        // TODO add your handling code here:
        
        JTxtCambio.setText("0.0");
    }//GEN-LAST:event_JBFacturacionActionPerformed
    public boolean Generacion_Factura(){
        boolean Control= false;
        Factura.getNumeroFactura("Sin", "Centro_Costo");
        return Control;
    }
    private String getNumroFactura(){
        int Numero = 0;
        try {
            String Str_Sql = "Select Actual from Rango_Factura where prefijo ='FAC-NEL'";
            ResultSet Rs =  JBase_Datos.SQL_QRY(this.Cn,Str_Sql);
            while(Rs.next()){
                Numero = Rs.getInt("Actual");
            }
            Rs.close();
            Numero++;
            Str_Sql = "update Rango_Factura "
                    + "set Actual="+Numero
                    + " where prefijo ='FAC-NEL' ";
            boolean Guardar = JBase_Datos.Exc_Sql(this.Cn,Str_Sql);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this," getNumroFactura(): "+e.getMessage());
        }
        return ""+Numero;
    }
    
    private void JBAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBAgregarActionPerformed
        // TODO add your handling code here:
        //AQUI SOLO AGREGA PRODUCTOS EN LA TABLA DE LA PANTALLA
        if( (!this.JTxtPlu.getText().trim().equals("") && !JTxtCantidad.getText().trim().equals("")) || ((!this.jCodigoBarra.getText().trim().equals("") && !JTxtCantidad.getText().trim().equals(""))   ) ){
            if ( this.Articulo.getArticulo_Plu(this.JTxtPlu.getText().trim()) || (this.SwCodigoBarra) ){
                this.AgregarProducto();
                this.JTxtCambio.setText(JFormato.format( this.Acomula_Medios_pagos- this.AcomuladoTotal_Pagar )); 
            }else{
                JOptionPane.showMessageDialog(this," Articulo no existe ");
            }
            
        }else{
            JOptionPane.showMessageDialog(this," Debe ingresar el Plu/Cantidad ");
        }
    }//GEN-LAST:event_JBAgregarActionPerformed

    private void JTxtPluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTxtPluActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTxtPluActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.setBorrarFila_tabla();
        this.JTxtCambio.setText(JFormato.format( this.Acomula_Medios_pagos- this.AcomuladoTotal_Pagar )); 
        JTxtTotalPagar.setText(JFormato.format(this.AcomuladoTotal_Pagar));
    }//GEN-LAST:event_jButton5ActionPerformed

    private void JCTipoMedioPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCTipoMedioPagoActionPerformed
        // TODO add your handling code here:
          if (!this.JCTipoMedioPago.getSelectedItem().toString().trim().equals("") && !this.JCTipoMedioPago.getSelectedItem().toString().trim().equals("Efectivo")){
            this.JLNumeroDocumento.setVisible(true);
            this.JTxtDocumento.setVisible(true);
        }else{
            this.JLNumeroDocumento.setVisible(false);
            this.JTxtDocumento.setVisible(false);
        }
    }//GEN-LAST:event_JCTipoMedioPagoActionPerformed

    private void JCTipoMedioPagoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JCTipoMedioPagoKeyPressed
        // TODO add your handling code here:
        if (!this.JCTipoMedioPago.getSelectedItem().toString().trim().equals("") && !this.JCTipoMedioPago.getSelectedItem().toString().trim().equals("Efectivo")){
            this.JLNumeroDocumento.setVisible(true);
            this.JTxtDocumento.setVisible(true);
        }else{
            this.JLNumeroDocumento.setVisible(false);
            this.JTxtDocumento.setVisible(false);
        }
    }//GEN-LAST:event_JCTipoMedioPagoKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            if(!this.JTxtValor.getText().trim().equals("") && !JCTipoMedioPago.getSelectedItem().toString().trim().equals("")){
                double Vlr = Double.parseDouble(this.JTxtValor.getText());
                
                this.Detalle_Medio = new Vector();
                this.Detalle_Medio.add(JCTipoMedioPago.getSelectedItem().toString().trim());
                this.Detalle_Medio.add(""+Vlr);
                this.M_Detalle.add(this.Detalle_Medio);
                
                this.Acomula_Medios_pagos = this.Acomula_Medios_pagos + Vlr;
                this.JTxtMedioPago.setText(JFormato.format(this.Acomula_Medios_pagos));
                this.JTxtValor.setText("");
                this.JTxtCambio.setText(JFormato.format( this.Acomula_Medios_pagos- this.AcomuladoTotal_Pagar ));   
            }else{
                JOptionPane.showMessageDialog(this,"Debes ingresar el Valor/Medio de Pago");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Click "+e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        this.Cabecera_Medio.addElement("Medio de Pago");
        this.Cabecera_Medio.addElement("Valor");
        MediosPagos = new JMedios(this.Cabecera_Medio, this.M_Detalle);
        this.MediosPagos.setBounds(300, 80, 320, 230);
        this.MediosPagos.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton6KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6KeyPressed

    private void JTxtPluKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTxtPluKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==115){
           Fr_Articulo = new JBuscar_Articulo(this.JBase_Datos, this.Cn, this);
           Fr_Articulo.setBounds(30,80, 500, 310);
           Fr_Articulo.setVisible(true);
        }
    }//GEN-LAST:event_JTxtPluKeyPressed
    
    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
        // TODO add your handling code here:
        
        //if(this.setTableArticulos()){
            if(this.setEncabezadoFactura()){
                JOptionPane.showMessageDialog(this,"Factura Guarda de Forma Correcta ");
            }
        //}
                
    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        impresora imp = new impresora(this.JBase_Datos , this.Cn);
        try {
            imp.Imprimir(this.TxtNoFactura.getText().trim());
            try {
                imp.Bandeja();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(JFacturacion.class.getName()).log(Level.SEVERE, null, ex);
            } catch (PrintException ex) {
                Logger.getLogger(JFacturacion.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (IOException ex) {
            Logger.getLogger(JFacturacion.class.getName()).log(Level.SEVERE, null, ex);
        }
        
                String options[] = {"Si", "No"}; //Respuestas
        int k;
        k = JOptionPane.showOptionDialog(null,
                "¿Dese crear una nueva Factura? ",
                "Facturacion",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                options,
                options[0]);
        if(k==0){
            //Crear Factura
            JFacturacion Ft = new JFacturacion(this.Principal,this.JBase_Datos, this.Cn, this.CentroVenta, this.Caja);
            Ft.setVisible(true);
            Principal.add(Ft);
            Principal.repaint();
            this.dispose();
        }
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jBImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBImprimirActionPerformed
        // TODO add your handling code here:
        impresora imp = new impresora(this.JBase_Datos , this.Cn);
        try {
            imp.Imprimir(this.TxtNoFactura.getText().trim());
            try {
                imp.Bandeja();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(JFacturacion.class.getName()).log(Level.SEVERE, null, ex);
            } catch (PrintException ex) {
                Logger.getLogger(JFacturacion.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (IOException ex) {
            Logger.getLogger(JFacturacion.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        String options[] = {"Si", "No"}; //Respuestas
        int k;
        k = JOptionPane.showOptionDialog(null,
                "¿Dese crear una nueva Factura? ",
                "Facturacion",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                options,
                options[0]);
        if(k==0){
            //Crear Factura
            JFacturacion Ft = new JFacturacion(this.Principal,this.JBase_Datos, this.Cn, this.CentroVenta, this.Caja);
            Ft.setVisible(true);
            Principal.add(Ft);
            Principal.repaint();
            this.dispose();
        }
    }//GEN-LAST:event_jBImprimirActionPerformed

    private void jBNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevoActionPerformed
        // TODO add your handling code here:
        JFacturacion Ft = new JFacturacion(this.Principal,this.JBase_Datos, this.Cn, this.CentroVenta, this.Caja);
        Ft.setVisible(true);
        Principal.add(Ft);
        Principal.repaint();
        this.dispose();
        
    }//GEN-LAST:event_jBNuevoActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        JFacturacion Ft = new JFacturacion(this.Principal,this.JBase_Datos, this.Cn, this.CentroVenta, this.Caja);
        Ft.setVisible(true);
        Principal.add(Ft);
        Principal.repaint();
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
       try{ 
            String Codigo = JOptionPane.showInputDialog("Codigo de Autorizacion: ");
            if(!Codigo.trim().equals("")){
                String Str_Sql = "select * from JUsuarios where Estado ='descuento' and clave='"+Codigo+"'";
                ResultSet Rs =  JBase_Datos.SQL_QRY(this.Cn,Str_Sql);
                if(Rs.next()){
                    String TValor ="";
                    while(TValor.trim().equals("")){
                        TValor = JOptionPane.showInputDialog("Ingrese el Valor: ");
                    }
                    this.Valor_Descuento_General = 0;
                    if (!TValor.trim().equals("")){
                        this.Valor_Descuento_General  = Double.valueOf(TValor);
                    }
                    this.AcomuladoTotal_Pagar = this.AcomuladoTotal_Pagar - this.Valor_Descuento_General;
                    this.JTxtTotalPagar.setText(JFormato.format(this.AcomuladoTotal_Pagar));
                    this.JTxtCambio.setText(JFormato.format( this.Acomula_Medios_pagos- this.AcomuladoTotal_Pagar )); 
                }
            }
        }catch(Exception e){
                JOptionPane.showMessageDialog(this,"Rutina de Decuento General()"+e.getMessage());
        }
        
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        //JTablaArticulos.getRowCount()
        if(JTablaArticulos.getRowCount()==0){
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(this,"Para poder salir debes Sacar la mercancia de Pantalla");
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed
    public boolean setEncabezadoFactura(){
        boolean Guardar = false;
        try {
            String Str_Sql= "Select * from JCabFactura where Numero ='"+TxtNoFactura.getText().trim()+"'";
            ResultSet Rs =  JBase_Datos.SQL_QRY(this.Cn,Str_Sql);
            if(!Rs.next()){
               Str_Sql = "Insert into JCabFactura (Numero,Fecha,Hora,CodigoCentoCosto,CodigoCajero,TotalIva,TotalOtroImpuesto,TotaPagar,CodigoMedio,Saldo_Plan_Separe,Descuento,Estado) VALUES "
                        + "('"+this.TxtNoFactura.getText().trim()+"','"+JTxtFecha.getText().trim()+"','"+this.getHoraActual()+"','"+this.CentroVenta.getCodigoCentroCosto().trim()+"','"+this.Caja.getCodigoCajeros().trim()+"', "+this.AcomuladoIva+","+this.AcomuladoOtroImpuesto+","+this.AcomuladoTotal_Pagar+",'"+ "Codigo Medio ',"+this.Acomulado_Plan_Separe+","+this.Valor_Descuento_General+",'C') ";
            }
            else{
                Str_Sql = "update  JCabFactura "
                        + "set Fecha='"+this.JTxtFecha.getText().trim()+"'"
                        + " ,Hora ='"+this.getHoraActual()+"'"
                        + " ,CodigoCentoCosto='"+this.CentroVenta.getCodigoCentroCosto()+"'"
                        + " ,CodigoCajero='"+this.Caja.getCodigoCajeros()+"'"
                        + " ,TotalIva="+this.AcomuladoIva
                        + " ,TotalOtroImpuesto="+this.AcomuladoOtroImpuesto
                        + " ,TotaPagar="+this.AcomuladoTotal_Pagar
                        + " ,CodigoMedio='Medio'"
                        + " ,Saldo_Plan_Separe="+this.Acomulado_Plan_Separe
                        + ", Descuento = "+this.Valor_Descuento_General
                        + " where Numero ='"+TxtNoFactura.getText().trim()+"'";
            }
            
            Guardar = JBase_Datos.Exc_Sql(this.Cn,Str_Sql);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"setEncabezadoFactura() "+e.getMessage());
        }
        return Guardar;
    }
    //Este procedimiento agrage de una en una 
    public boolean setTable_Articulos(String PArticulo, int PCantidad, double PPrecio, double PPrecioTotal){
        boolean Guardo = false;
        try {
                    double Precio = 0, PrecioTotal = 0;
                    int Cant = 0;
                    Cant = PCantidad;
                    Precio = PPrecio;
                    PrecioTotal =PPrecioTotal;
                    Guardo = this.setDetalleFactura(PArticulo,Precio, Cant, PrecioTotal);
                    if(Guardo==false){
                        JOptionPane.showMessageDialog(this," El plu "+PArticulo+" No se puedo guardar de forma Correecta");   
                    }else{
                       //JOptionPane.showMessageDialog(this," El plu "+PArticulo+" Se Guardo Correctamente");   
                    }
                        
                    //Guardar el movimiento en el Maestro de Movimientos......
                    this.Articulo.Movimiento(""+PArticulo, Cant, "Vent_Fac_"+TxtNoFactura.getText().trim(), "-");
                
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"setTableArticulos() "+e.getMessage());
        }
        return Guardo;
    }
    
    
    
    
    
    //AGREGAR DE FORMA RECURSIVA DESDE EL BOTOPN GUARDAR
    public boolean setTableArticulos(){
        boolean Guardo = false;
        try {
            int Item = 0;
            int Cantidad = JTablaArticulos.getRowCount()-1;
            if(JTxtCambio.getText().equals("0.0")){
                while(Item<=Cantidad){
                    double Precio = 0, PrecioTotal = 0;
                    int Cant = 0;
                    String Tmp = "";
                    Tmp= String.valueOf(JTablaArticulos.getValueAt(Item,2));
                    Cant = Integer.parseInt(Tmp.trim());
                    Precio = Double.parseDouble(JTablaArticulos.getValueAt(Item,3).toString());
                    PrecioTotal =Double.parseDouble(JTablaArticulos.getValueAt(Item,3).toString())*Cant;
                    
                    Guardo = this.setDetalleFactura(JTablaArticulos.getValueAt(Item,0).toString().trim(),Precio, Cant, PrecioTotal);
                    if(Guardo==false){
                        JOptionPane.showMessageDialog(this," El plu "+Tmp+" No se puedo guardar de forma Correecta");   
                    }
                    //Guardar el movimiento en el Maestro de Movimientos......
                    this.Articulo.Movimiento(""+JTablaArticulos.getValueAt(Item,0), Cant, "Vent_Fac_"+TxtNoFactura.getText().trim(), "-");
                    Item++;
                }
            }else{
               JOptionPane.showMessageDialog(this," El saldo o cambio debe estar en Cero ");   
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"setTableArticulos() "+e.getMessage());
        }
        return Guardo;
    }
    public boolean setDetalleFactura(String plu, double PrecioUnitario,int Cantidad ,double PrecioTotal){
        boolean Guardar = false;
        try {
//                String Str_Sql = "select * from JDetFactura where Numero='"+TxtNoFactura.getText().trim()+"' "
//                        + "and plu='"+plu+"'";
//                ResultSet Rs =  JBase_Datos.SQL_QRY(this.Cn,Str_Sql);
//                if(!Rs.next()){
                    String Str_Sql ="insert into JDetFactura (Numero,Plu,PrecioUnitario,Cantidad,TotalItem) Values"
                            + "('"+TxtNoFactura.getText().trim()+"','"+plu+"',"+PrecioUnitario+","+Cantidad+","+PrecioTotal+")";
//                }else{
//                    Str_Sql ="update JDetFactura "
//                            + "set PrecioUnitario= "+PrecioUnitario
//                            + ", Cantidad="+Cantidad
//                            + ", TotalItem="+PrecioTotal
//                            + " where Numero='"+TxtNoFactura.getText().trim()+"' and plu='"+plu+"'";
//                }
//                
                Guardar = JBase_Datos.Exc_Sql(this.Cn,Str_Sql);
         
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"setDetalleFactura() "+e.getMessage());
        }
        return Guardar;
    }
    
    public void getAsignarMediosPagos(){
        try{
            String Str_Sql = "select  CodigoMedio, Descripcion from  JMediosPagos "
                        +"where Estado ='activo' ";
            JCTipoMedioPago.removeAllItems();
            JCTipoMedioPago.addItem("");
            ResultSet xResult =  JBase_Datos.SQL_QRY(this.Cn,Str_Sql);
            while(xResult.next()){
                JCTipoMedioPago.addItem(xResult.getString("Descripcion").trim());
            }
            xResult.close();
       }catch(Exception e ){
           JOptionPane.showMessageDialog(this,"JCentroCosto"+e.getMessage());
       }
       
    }
    
    public javax.swing.JTable getTablaArticulo(){
        return this.JTablaArticulos;
    } 
 
    public boolean EliminaTabla(String Codigo){
        boolean Control = true;
        try {
            String Str_Sql = "delete from JDetFactura where Numero='"+TxtNoFactura.getText().trim()+"' and Plu='"+Codigo+"'";
            Control =  JBase_Datos.Exc_Sql(this.Cn,Str_Sql);
            if(Control){
                //JOptionPane.showMessageDialog(this,"Eliminado el Plu "+Codigo); 
            }else{
                JOptionPane.showMessageDialog(this,"NO SE PUDO Eliminado el Plu "+Codigo);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"EliminaTabla() "+e.getMessage()); 
        }
        return Control;
    }
    public void setTxtPlu(String Pl){
        this.JTxtPlu.setText(Pl.trim());
    }
    public void setBorrarFila_tabla(){
       try{ 
           String Codigo = JTablaArticulos.getValueAt(JTablaArticulos.getSelectedRow(),0).toString().trim();
            if (EliminaTabla(Codigo)){
                //String Codigo = JTablaArticulos.getValueAt(JTablaArticulos.getSelectedRow(),0).toString().trim();
                this.Cantidad = Double.parseDouble(JTablaArticulos.getValueAt(JTablaArticulos.getSelectedRow(),2).toString().trim());
                this.Articulo.getArticulo_Plu(Codigo);
                this.Articulo.Movimiento(""+JTablaArticulos.getValueAt(JTablaArticulos.getSelectedRow(),0), this.Cantidad, "Elimina_Vent_Fac_"+TxtNoFactura.getText().trim(), "+");
                this.Descontar = Double.parseDouble(JTablaArticulos.getValueAt(JTablaArticulos.getSelectedRow(),3).toString().trim());
                CalcularValor_Pagar("Negativo");
                CalculaImpuestos("Negativo");
                DefaultTableModel Modelo =(DefaultTableModel) this.JTablaArticulos.getModel();
                Modelo.removeRow(this.JTablaArticulos.getSelectedRow());
                this.JTablaArticulos.updateUI();
                this.PosionActual --;
                
            }
       }catch(Exception e){
           JOptionPane.showMessageDialog(this,"El registro seleccionado debe Contener informacion"); 
       }
    }
     
    public String getFecha(){
        Date ahora = new Date();
        SimpleDateFormat formateador = new SimpleDateFormat("yyyyMMdd");
        return formateador.format(ahora);
    }
    public String getHoraActual() {
        Date ahora = new Date();
        SimpleDateFormat formateador = new SimpleDateFormat("hh:mm:ss");
        return formateador.format(ahora);
    }
    public java.sql.Date sumarFechasDias(java.sql.Date fch, int dias) {
        Calendar cal = new GregorianCalendar();
        cal.setTimeInMillis(fch.getTime());
        cal.add(Calendar.DATE, dias);
        return new java.sql.Date(cal.getTimeInMillis());
    }
    public synchronized java.sql.Date restarFechasDias(java.sql.Date fch, int dias) {
        Calendar cal = new GregorianCalendar();
        cal.setTimeInMillis(fch.getTime());
        cal.add(Calendar.DATE, -dias);
        return new java.sql.Date(cal.getTimeInMillis());
    }
    
     //Diferencias entre dos fechas
    //@param fechaInicial La fecha de inicio
    //@param fechaFinal  La fecha de fin
    //@return Retorna el numero de dias entre dos fechas
    public static synchronized int diferenciasDeFechas(Date fechaInicial, Date fechaFinal) {

        DateFormat df = DateFormat.getDateInstance(DateFormat.MEDIUM);
        String fechaInicioString = df.format(fechaInicial);
        try {
            fechaInicial = df.parse(fechaInicioString);
        } catch (ParseException ex) {
        }

        String fechaFinalString = df.format(fechaFinal);
        try {
            fechaFinal = df.parse(fechaFinalString);
        } catch (ParseException ex) {
        }

        long fechaInicialMs = fechaInicial.getTime();
        long fechaFinalMs = fechaFinal.getTime();
        long diferencia = fechaFinalMs - fechaInicialMs;
        double dias = Math.floor(diferencia / (1000 * 60 * 60 * 24));
        return ((int) dias);
    }

    

    public int BuscarProd_Tabla(){
        int Control = -1;
        for (int i = 0; i <= this.PosionActual; i++) {
            String Plu ="";
            //Plu = String.valueOf(Detalle[i][0]);
            if( Plu.equals(this.Articulo.getPlu()) ){
                Control = i;
                i= PosionActual+1;
            }
        }
        return Control;
    }
    public void CalcularValor_Pagar(String Tipo){
        try {
            double Vlr = 0;
            if(Tipo.trim().equals("Positivo")){
                Vlr = this.Articulo.getPrecioVenta() * this.Cantidad;
                AcomuladoTotal_Pagar = AcomuladoTotal_Pagar + Vlr;
            }
            if(Tipo.trim().equals("Negativo")){
                Vlr = Descontar * this.Cantidad;
                AcomuladoTotal_Pagar = AcomuladoTotal_Pagar - Vlr;
            }
            this.JTxtTotalPagar.setText(JFormato.format(this.AcomuladoTotal_Pagar));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"CalcularValor_Pagar() "+e.getMessage()); 
        }
    }
    public void CalculaImpuestos(String Tipo){
        //Antes de Usarse de debe Ubicarse en memoria en el articulo y establecer la cantidad
        try {
            double VlrIva = 0;
            double VlrOtro= 0;
            if(Tipo.equals("Positivo")){

                VlrIva  = ( this.Articulo.getPrecioVenta() * (this.Articulo.getPorcentajeIva()/100))*this.Cantidad;
                VlrOtro = ( this.Articulo.getPrecioVenta() *(this.Articulo.getPorcentajeOtro()/100)) * this.Cantidad;
                this.AcomuladoIva = this.AcomuladoIva + VlrIva;
                this.AcomuladoOtroImpuesto = this.AcomuladoOtroImpuesto + VlrOtro;
            }
            if(Tipo.equals("Negativo")){
                VlrIva  = ( this.Articulo.getPrecioVenta() * (this.Articulo.getPorcentajeIva()/100))*this.Cantidad;
                VlrOtro = ( this.Articulo.getPrecioVenta() *(this.Articulo.getPorcentajeOtro()/100) ) * this.Cantidad;
                this.AcomuladoIva = this.AcomuladoIva - VlrIva;
                this.AcomuladoOtroImpuesto = this.AcomuladoOtroImpuesto - VlrOtro;
            }
            this.JTxtIva.setText(JFormato.format(this.AcomuladoIva));
            this.JTxtOtros.setText(JFormato.format(this.AcomuladoOtroImpuesto));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"CalculaImpuestos()"+e.getMessage()); 
        }
    }
    
    public void AgregarProducto(){
        try {
            if(!jTxtDescuento.getText().equals("0")){
                
            }
                double TmpPrecioVenta = 0;
                try {
                    TmpPrecioVenta = Double.parseDouble(jTxtDescuento.getText().trim());
                } catch (Exception e) {
                }
                //Aplica el descuento.
                TmpPrecioVenta = this.Articulo.getPrecioVenta() - TmpPrecioVenta;
                //Configurar nuevo precio del articulo segun el descuento
                this.Articulo.setPrecioVenta(TmpPrecioVenta);
                
                if ((TmpPrecioVenta>= this.Articulo.getPrecioVentaMinimo())&& (TmpPrecioVenta<=this.Articulo.getPrecioVenta())) {
                    
                    this.Cantidad = Double.parseDouble(this.JTxtCantidad.getText());
                    this.Detalle = new Vector();
            
                    Detalle.add( this.Articulo.getPlu().trim());
                    Detalle.add(this.Articulo.getNombreLargo().trim());
                    Detalle.add(Integer.parseInt(this.JTxtCantidad.getText()));
                    Detalle.add(TmpPrecioVenta);
                    Detalle.add(TmpPrecioVenta*Double.parseDouble(this.JTxtCantidad.getText()));
                    int XCant =Integer.parseInt(this.JTxtCantidad.getText());
                    this.Art_Detalle.add(Detalle);
                    this.setTable_Articulos(this.Articulo.getPlu().trim(), XCant, TmpPrecioVenta, (TmpPrecioVenta*XCant));
                    this.CalculaImpuestos("Positivo");
                    this.CalcularValor_Pagar("Positivo");
                    JTablaArticulos.setModel(new javax.swing.table.DefaultTableModel(this.Art_Detalle, Cabecera));
            
                    this.jCodigoBarra.setText("");
                    this.JTxtCantidad.setText("");
                    this.JTxtPlu.setText("");
                    this.jCodigoBarra.setText("");
                    this.jTxtDescuento.setText("0");
                    this.SwCodigoBarra = false;
                }else{
                    JOptionPane.showMessageDialog(this,"Precio de Venta No autorizado "); 
                }
             
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"AgregarProducto()"+e.getMessage()); 
        }
    }
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFacturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFacturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFacturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFacturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new JFacturacion(null, null, null, null, null).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBAgregar;
    private javax.swing.JButton JBFacturacion;
    private javax.swing.JComboBox JCTipoMedioPago;
    private javax.swing.JLabel JLNumeroDocumento;
    private javax.swing.JTable JTablaArticulos;
    private javax.swing.JTextField JTxtCambio;
    private javax.swing.JTextField JTxtCantidad;
    private javax.swing.JTextField JTxtDocumento;
    private javax.swing.JTextField JTxtFecha;
    private javax.swing.JTextField JTxtIva;
    private javax.swing.JTextField JTxtMedioPago;
    private javax.swing.JTextField JTxtNombreCajero;
    private javax.swing.JTextField JTxtOtros;
    private javax.swing.JTextField JTxtPlu;
    private javax.swing.JTextField JTxtTotalPagar;
    private javax.swing.JTextField JTxtValor;
    private javax.swing.JTextField TxtNoFactura;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBImprimir;
    private javax.swing.JButton jBNuevo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JTextField jCodigoBarra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField jTxtDescuento;
    // End of variables declaration//GEN-END:variables

}
